//! Purity / robustness properties (ADR-0015 §7): no panic over positions
//! generated by random legal playouts through the engine, `choose`'s
//! some-iff-legal-moves contract, and history bookkeeping along the way.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use std::collections::BTreeMap;

use proptest::prelude::*;
use sashite_sanki_engine::engine;
use sashite_sanki_player::{choose, Context, Limits, Occurrences, Position, Strength};

/// Start positions across the variant space — same-variant and
/// cross-variant, hands included.
const STARTS: [&str; 3] = [
    // Chess vs chess, the full array.
    "rnbqk^bnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQK^BNR / W/w",
    // Ōgi vs ōgi with a hand (drops in the move space).
    "k^7/2B5/1K^6/7f/8/8/8/8 R/ J/j",
    // Cross-variant: xiongqi (first) vs chess (second), an EP marker on board.
    "k^2b4/8/6S1/r4-pG^1/5n2/8/8/8 / C/w",
];

/// A deterministic playout: from `start`, play `plies` moves, each picked by
/// `seed` over the canonically-sorted legal list, maintaining the kernel's
/// occurrence bookkeeping. Returns the reached context ingredients.
fn playout(start: &str, plies: u8, seed: u64) -> (Position, Occurrences, u32) {
    let mut position = Position::parse(start).expect("start FEEN parses");
    let mut occurrences: Occurrences = BTreeMap::new();
    occurrences.insert(position.to_feen(), 1);
    let mut clock = 0_u32;
    let mut state = seed;

    for _ in 0..plies {
        let mut moves = engine::legal_moves(&position);
        if moves.is_empty() {
            break;
        }
        moves.sort_by_key(|mv| format!("{mv:?}"));
        // SplitMix64 step (kept local: the crate's PRNG is private).
        state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        let pick = (z ^ (z >> 31)) as usize % moves.len();
        let mv = moves[pick].clone();
        let resets = sashite_sanki_player::classify::resets_halfmove_clock(&position, &mv);
        let Ok(next) = engine::apply(&position, &mv) else {
            break;
        };
        position = next;
        clock = if resets { 0 } else { clock + 1 };
        *occurrences.entry(position.to_feen()).or_insert(0) += 1;
    }
    (position, occurrences, clock)
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(12))]

    /// `choose` never panics on played-out positions, and returns a move
    /// exactly when the engine has one.
    #[test]
    fn choose_is_total_over_playouts(
        start_index in 0_usize..STARTS.len(),
        plies in 0_u8..14,
        seed in any::<u64>(),
    ) {
        let (position, occurrences, clock) = playout(STARTS[start_index], plies, seed);
        let ctx = Context {
            position: &position,
            occurrences: &occurrences,
            halfmove_clock: clock,
        };
        let strength = Strength { max_depth: 2, tt_capacity: 10_000, seed, ..Strength::default() };
        let limits = Limits { max_nodes: Some(3_000), should_stop: None };
        let choice = choose(&ctx, &strength, &limits);
        let has_moves = !engine::legal_moves(&position).is_empty();
        prop_assert_eq!(choice.is_some(), has_moves);
        if let Some(choice) = choice {
            // The chosen move is legal, and the PV opens with it.
            prop_assert!(engine::legal_moves(&position).contains(&choice.mv));
            prop_assert_eq!(choice.pv.first(), Some(&choice.mv));
            prop_assert!(choice.depth >= 1);
        }
    }
}
